services:
  mysql:
    image: 'mysql:oraclelinux9'
    container_name: mysql_estapar
    platform: linux/amd64/v8
    environment:
      - 'MYSQL_DATABASE=estapar'
      - 'MYSQL_PASSWORD=estaparsecret'
      - 'MYSQL_ROOT_PASSWORD=estaparsecret'
      - 'MYSQL_USER=estapar'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - 'estapar'

volumes:
  mysql_data:

networks:
  estapar:
